let KEY_PRICE_BUY = 3.5
let KEY_PRICE_SELL = 3.4
let WITHDRAWAL_FEES = 0.05
let WITHDRAWAL_MIN = 10

module.exports.KEY_PRICE_BUY = KEY_PRICE_BUY
module.exports.KEY_PRICE_SELL = KEY_PRICE_SELL
module.exports.WITHDRAWAL_FEES = WITHDRAWAL_FEES
module.exports.WITHDRAWAL_MIN = WITHDRAWAL_MIN
